all: build run

# если не указать правило, будет выполнено первое правило
build:
# -lmingw32 -lSDL2main в таком порядке позволяет избежать ошибки <undefined reference to 'WinMain'>
# lm - математическая библиотека
	gcc -Wall -std=c99 ./src/*.c -lmingw32 -lSDL2main -lSDL2 -lm -o renderer

.PHONY: run clean

run:
	./renderer.exe

clean:
	del .\renderer.exe

release:
	gcc -O3 -Wall -std=c99 ./src/*.c -lmingw32 -lSDL2main -lSDL2 -lm -o renderer